// FANCY LOADER https://codepen.io/miocene/pen/WNLQKEJ 
// credit Julia Miocene

const FancyLoader = () => (
    <div className="loader rainbow">
        <div className="circle" style={{ "--i": "1" }}></div>
        <div className="circle" style={{ "--i": "2" }}></div>
        <div className="circle" style={{ "--i": "3" }}></div>
        <div className="circle" style={{ "--i": "4" }}></div>
        <div className="circle" style={{ "--i": "5" }}></div>
        <div className="circle" style={{ "--i": "6" }}></div>
        <div className="circle" style={{ "--i": "7" }}></div>
        <div className="circle" style={{ "--i": "8" }}></div>
        <div className="circle" style={{ "--i": "9" }}></div>
        <div className="circle" style={{ "--i": "10" }}></div>
        <div className="circle" style={{ "--i": "11" }}></div>
        <div className="circle" style={{ "--i": "12" }}></div>
        <div className="circle" style={{ "--i": "13" }}></div>
        <div className="circle" style={{ "--i": "14" }}></div>
        <div className="circle" style={{ "--i": "15" }}></div>
        <div className="circle" style={{ "--i": "16" }}></div>
        <div className="circle" style={{ "--i": "17" }}></div>
        <div className="circle" style={{ "--i": "18" }}></div>
        <div className="circle" style={{ "--i": "19" }}></div>
        <div className="circle" style={{ "--i": "20" }}></div>
        <div className="circle" style={{ "--i": "21" }}></div>
        <div className="circle" style={{ "--i": "22" }}></div>
        <div className="circle" style={{ "--i": "23" }}></div>
        <div className="circle" style={{ "--i": "24" }}></div>
        <div className="circle" style={{ "--i": "25" }}></div>
        <div className="circle" style={{ "--i": "26" }}></div>
        <div className="circle" style={{ "--i": "27" }}></div>
        <div className="circle" style={{ "--i": "28" }}></div>
        <div className="circle" style={{ "--i": "29" }}></div>
        <div className="circle" style={{ "--i": "30" }}></div>
        <div className="circle" style={{ "--i": "31" }}></div>
        <div className="circle" style={{ "--i": "32" }}></div>
        <div className="circle" style={{ "--i": "33" }}></div>
        <div className="circle" style={{ "--i": "34" }}></div>
        <div className="circle" style={{ "--i": "35" }}></div>
        <div className="circle" style={{ "--i": "36" }}></div>
        <div className="circle" style={{ "--i": "37" }}></div>
        <div className="circle" style={{ "--i": "38" }}></div>
        <div className="circle" style={{ "--i": "39" }}></div>
        <div className="circle" style={{ "--i": "40" }}></div>
        <div className="circle" style={{ "--i": "41" }}></div>
        <div className="circle" style={{ "--i": "42" }}></div>
        <div className="circle" style={{ "--i": "43" }}></div>
        <div className="circle" style={{ "--i": "44" }}></div>
        <div className="circle" style={{ "--i": "45" }}></div>
        <div className="circle" style={{ "--i": "46" }}></div>
        <div className="circle" style={{ "--i": "47" }}></div>
        <div className="circle" style={{ "--i": "48" }}></div>
        <div className="circle" style={{ "--i": "49" }}></div>
        <div className="circle" style={{ "--i": "50" }}></div>
        <div className="circle" style={{ "--i": "51" }}></div>
        <div className="circle" style={{ "--i": "52" }}></div>
        <div className="circle" style={{ "--i": "53" }}></div>
        <div className="circle" style={{ "--i": "54" }}></div>
        <div className="circle" style={{ "--i": "55" }}></div>
        <div className="circle" style={{ "--i": "56" }}></div>
        <div className="circle" style={{ "--i": "57" }}></div>
        <div className="circle" style={{ "--i": "58" }}></div>
        <div className="circle" style={{ "--i": "59" }}></div>
        <div className="circle" style={{ "--i": "60" }}></div>
        <div className="circle" style={{ "--i": "61" }}></div>
        <div className="circle" style={{ "--i": "62" }}></div>
        <div className="circle" style={{ "--i": "63" }}></div>
        <div className="circle" style={{ "--i": "64" }}></div>
        <div className="circle" style={{ "--i": "65" }}></div>
        <div className="circle" style={{ "--i": "66" }}></div>
        <div className="circle" style={{ "--i": "67" }}></div>
        <div className="circle" style={{ "--i": "68" }}></div>
        <div className="circle" style={{ "--i": "69" }}></div>
        <div className="circle" style={{ "--i": "70" }}></div>
        <div className="circle" style={{ "--i": "71" }}></div>
        <div className="circle" style={{ "--i": "72" }}></div>
        <div className="circle" style={{ "--i": "73" }}></div>
        <div className="circle" style={{ "--i": "74" }}></div>
        <div className="circle" style={{ "--i": "75" }}></div>
        <div className="circle" style={{ "--i": "76" }}></div>
        <div className="circle" style={{ "--i": "77" }}></div>
        <div className="circle" style={{ "--i": "78" }}></div>
        <div className="circle" style={{ "--i": "79" }}></div>
        <div className="circle" style={{ "--i": "80" }}></div>
        <div className="circle" style={{ "--i": "81" }}></div>
        <div className="circle" style={{ "--i": "82" }}></div>
        <div className="circle" style={{ "--i": "83" }}></div>
        <div className="circle" style={{ "--i": "84" }}></div>
        <div className="circle" style={{ "--i": "85" }}></div>
        <div className="circle" style={{ "--i": "86" }}></div>
        <div className="circle" style={{ "--i": "87" }}></div>
        <div className="circle" style={{ "--i": "88" }}></div>
        <div className="circle" style={{ "--i": "89" }}></div>
        <div className="circle" style={{ "--i": "90" }}></div>
        <div className="circle" style={{ "--i": "91" }}></div>
        <div className="circle" style={{ "--i": "92" }}></div>
        <div className="circle" style={{ "--i": "93" }}></div>
        <div className="circle" style={{ "--i": "94" }}></div>
        <div className="circle" style={{ "--i": "95" }}></div>
        <div className="circle" style={{ "--i": "96" }}></div>
        <div className="circle" style={{ "--i": "97" }}></div>
        <div className="circle" style={{ "--i": "98" }}></div>
        <div className="circle" style={{ "--i": "99" }}></div>
        <div className="circle" style={{ "--i": "100" }}></div>
    </div>
)

export default FancyLoader;